IMDC\TerpTubeBundle\Entity\UserGroup:
  exclusion_policy: ALL
  virtual_properties:
    getOrderedMedia:
      serialized_name: ordered_media
  properties:
    id:
      expose: true
    name:
      expose: true
