IMDC\TerpTubeBundle\Entity\Post:
  exclusion_policy: ALL
  virtual_properties:
    getOrderedMedia:
      serialized_name: ordered_media
    isPostReply:
      serialized_name: is_post_reply
  properties:
    id:
      expose: true
    content:
      expose: true
    edited_at:
      expose: true
    startTime:
      expose: true
    endTime:
      expose: true
    isTemporal:
      expose: true
    parentPost:
      expose: true
    author:
      expose: true
    parentThread:
      expose: true
    editedBy:
      expose: true
