IMDC\TerpTubeBundle\Entity\Media:
  virtual_properties:
    isInterpretation:
      serialized_name: is_interpretation
  properties:
    thumbnailPath:
      access_type: public_method
      accessor:
        getter: getThumbnailPath
    owner:
      exclude: true
