IMDCTerpTubeBundle_default:
  resource: "@IMDCTerpTubeBundle/Resources/config/routing/default.yml"

IMDCTerpTubeBundle_forum:
  type: rest
  resource: "@IMDCTerpTubeBundle/Resources/config/routing/forum.yml"
  prefix: /forum

IMDCTerpTubeBundle_group:
  type: rest
  resource: "@IMDCTerpTubeBundle/Resources/config/routing/group.yml"
  prefix: /group

IMDCTerpTubeBundle_home:
  resource: "@IMDCTerpTubeBundle/Resources/config/routing/home.yml"
  prefix: /home

IMDCTerpTubeBundle_invitation:
  resource: "@IMDCTerpTubeBundle/Resources/config/routing/invitation.yml"
  prefix: /invitation

IMDCTerpTubeBundle_member:
  resource: "@IMDCTerpTubeBundle/Resources/config/routing/member.yml"
  prefix: /member

IMDCTerpTubeBundle_contact:
  resource: "@IMDCTerpTubeBundle/Resources/config/routing/contact.yml"
  prefix: /contacts

IMDCTerpTubeBundle_media:
  type: rest
  resource: "@IMDCTerpTubeBundle/Resources/config/routing/media.yml"

IMDCTerpTubeBundle_message:
  resource: "@IMDCTerpTubeBundle/Resources/config/routing/message.yml"
  prefix: /message

IMDCTerpTubeBundle_myFiles:
  resource: "@IMDCTerpTubeBundle/Resources/config/routing/myFiles.yml"
  prefix: /myFiles

IMDCTerpTubeBundle_post:
  type: rest
  resource: "@IMDCTerpTubeBundle/Resources/config/routing/post.yml"
  prefix: /post

IMDCTerpTubeBundle_profile:
  resource: "@IMDCTerpTubeBundle/Resources/config/routing/profile.yml"
  prefix: /profile

IMDCTerpTubeBundle_thread:
  resource: "@IMDCTerpTubeBundle/Resources/config/routing/thread.yml"
  prefix: /thread

IMDCTerpTubeBundle_help:
  resource: "@IMDCTerpTubeBundle/Resources/config/routing/help.yml"
  prefix: /help
