# IMDC/TerpTubeBundle/Resources/config/admin.yml

services:
    sonata.admin.post:
        class: IMDC\TerpTubeBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Post" }
        arguments:
            - ~
            - IMDC\TerpTubeBundle\Entity\Post
            - ~
        calls:
            - [ setTranslationDomain, [IMDCTerpTubeBundle]]
    sonata.admin.user:
        class: IMDC\TerpTubeBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Id", label: "User" }
        arguments:
            - ~
            - IMDC\TerpTubeBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [IMDCTerpTubeBundle]]
            