# IMDC/TerpTubeBundle/Resources/config/admin.yml

services:
    sonata.admin.post:
        class: IMDC\TerpTubeBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Posts", label: "Post" }
        arguments:
            - ~
            - IMDC\TerpTubeBundle\Entity\Post
            - ~
        calls:
            - [ setTranslationDomain, [IMDCTerpTubeBundle]]
    sonata.admin.user:
        class: IMDC\TerpTubeBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Users", label: "User" }
        arguments:
            - ~
            - IMDC\TerpTubeBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [IMDCTerpTubeBundle]]
            
    sonata.admin.message:
        class: IMDC\TerpTubeBundle\Admin\MessageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Messages", label: "Messages" }
        arguments:
            - ~
            - IMDC\TerpTubeBundle\Entity\Message
            - ~
        calls:
            - [ setTranslationDomain, [IMDCTerpTubeBundle]]
    
    sonata.admin.media:
        class: IMDC\TerpTubeBundle\Admin\MediaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Media", label: "Media" }
        arguments:
            - ~
            - IMDC\TerpTubeBundle\Entity\Media
            - ~
        calls:
            - [ setTranslationDomain, [IMDCTerpTubeBundle]]
            
    sonata.admin.usergroup:
        class: IMDC\TerpTubeBundle\Admin\UserGroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "UserGroup", label: "UserGroup" }
        arguments:
            - ~
            - IMDC\TerpTubeBundle\Entity\UserGroup
            - ~
        calls:
            - [ setTranslationDomain, [IMDCTerpTubeBundle]]