IMDCTerpTubeBundle_default:
  resource: "@IMDCTerpTubeBundle/Resources/config/routing/default.yml"

IMDCTerpTubeBundle_forum:
  resource: "@IMDCTerpTubeBundle/Resources/config/routing/forum.yml"
  prefix: /forums

IMDCTerpTubeBundle_group:
  resource: "@IMDCTerpTubeBundle/Resources/config/routing/group.yml"
  prefix: /groups

IMDCTerpTubeBundle_home:
  resource: "@IMDCTerpTubeBundle/Resources/config/routing/home.yml"
  prefix: /home

IMDCTerpTubeBundle_invitation:
  resource: "@IMDCTerpTubeBundle/Resources/config/routing/invitation.yml"
  prefix: /invitations

IMDCTerpTubeBundle_member:
  resource: "@IMDCTerpTubeBundle/Resources/config/routing/member.yml"
  prefix: /members

IMDCTerpTubeBundle_message:
  resource: "@IMDCTerpTubeBundle/Resources/config/routing/message.yml"
  prefix: /messages

IMDCTerpTubeBundle_myFiles:
  resource: "@IMDCTerpTubeBundle/Resources/config/routing/myFiles.yml"
  prefix: /myFiles

IMDCTerpTubeBundle_post:
  resource: "@IMDCTerpTubeBundle/Resources/config/routing/post.yml"
  prefix: /post

IMDCTerpTubeBundle_profile:
  resource: "@IMDCTerpTubeBundle/Resources/config/routing/profile.yml"
  prefix: /profile

IMDCTerpTubeBundle_thread:
  resource: "@IMDCTerpTubeBundle/Resources/config/routing/thread.yml"
  prefix: /thread

IMDCTerpTubeBundle_help:
  resource: "@IMDCTerpTubeBundle/Resources/config/routing/help.yml"
  prefix: /help












imdc_media_chooser_by_type:
  pattern: /myFiles/choose/{type}
  defaults: { _controller: IMDCTerpTubeBundle:MediaChooserGateway:chooseMediaByType, type: 0 }
  methods: [GET|POST]
  options:
    expose: true

imdc_media_simultaneous_record: 
    pattern: /media/record/simultaneous/{mediaID}
    defaults: { _controller: IMDCTerpTubeBundle:Media:simultaneousPreviewAndRecord, url: null }
    options:
        expose: true

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /rolegroup

IMDCTerpTubeBundle_permissions:
    resource: "@IMDCTerpTubeBundle/Resources/config/routing/permissions.yml"
    prefix: /permissions   

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
