imdc_terp_tube_homepage:
    pattern:  /
    defaults: { _controller: IMDCTerpTubeBundle:Default:index }
    
imdc_terp_tube_user_splash:
    pattern: /home/
    defaults: { _controller: IMDCTerpTubeBundle:Home:index }

imdc_terp_tube_user_profile_change-password:
    pattern: /profile/{userName}/change-password
    defaults: { _controller: FOSUserBundle:ChangePassword:changePassword }
    methods:  [GET|POST]
    
imdc_terp_tube_user_profile_specific:
    pattern: /profile/{userName}
    defaults: { _controller: IMDCTerpTubeBundle:Profile:showSpecific }
    
imdc_terp_tube_user_profile:
    pattern: /profile/
    defaults: { _controller: IMDCTerpTubeBundle:Profile:show }
    
imdc_terp_tube_user_avatar_edit: 
    pattern: /profile/{userName}/edit/avatar
    defaults: { _controller: IMDCTerpTubeBundle:Profile:updateAvatar }

imdc_terp_tube_user_profile_edit:
    pattern: /profile/{userName}/edit
    defaults: { _controller: IMDCTerpTubeBundle:Profile:edit }
    

imdc_media_chooser_by_type: 
    pattern: /myFiles/choose/{type}
    defaults: { _controller: IMDCTerpTubeBundle:MediaChooserGateway:chooseMediaByType, type: 0 }
    requirements:
        _method:  POST
    options:
        expose: true
        
imdc_files_gateway: 
    pattern: /myFiles
    defaults: { _controller: IMDCTerpTubeBundle:MyFilesGateway:gateway }
    
imdc_files_add_gateway: 
    pattern: /myFiles/add
    defaults: { _controller: IMDCTerpTubeBundle:AddFileGateway:gateway}
    
imdc_files_gateway_audio: 
    pattern: /myFiles/add/audio
    defaults: { _controller: IMDCTerpTubeBundle:AddFileGateway:addAudio, url: null }
    
imdc_files_gateway_video: 
    pattern: /myFiles/add/video
    defaults: { _controller: IMDCTerpTubeBundle:AddFileGateway:addVideo, url: null }
    
imdc_files_gateway_image: 
    pattern: /myFiles/add/image
    defaults: { _controller: IMDCTerpTubeBundle:AddFileGateway:addImage, url: null }
    
imdc_files_gateway_record_media: 
    pattern: /myFiles/recordMedia
    defaults: { _controller: IMDCTerpTubeBundle:MyFilesGateway:recordMedia, url: null }

imdc_files_gateway_other: 
    pattern: /myFiles/add/other
    defaults: { _controller: IMDCTerpTubeBundle:AddFileGateway:addOther, url: null }

imdc_files_gateway_remove: 
     pattern: /myFiles/delete/{mediaId}
     defaults: { _controller: IMDCTerpTubeBundle:MyFilesGateway:deleteMedia }
     requirements:
        _method:  POST
        mediaId: \d+
        
imdc_files_gateway_record: 
     pattern: /myFiles/record
     defaults: { _controller: IMDCTerpTubeBundle:AddFileGateway:addRecording, url: null }
     requirements:
        _method:  POST
        
imdc_files_gateway_preview:
    pattern: /myFiles/preview/{mediaId}
    defaults: { _controller: IMDCTerpTubeBundle:MyFilesGateway:previewMedia }
    requirements:
        _method:  POST
#        mediaId: \d+


imdc_message_create:
    pattern: /createMessage
    defaults: { _controller: IMDCTerpTubeBundle:Message:createMessage } 
        
imdc_message_user_specific:
    pattern: /createMessage/{userid}
    defaults: { _controller: IMDCTerpTubeBundle:Message:createMessage, userid:null }

imdc_message_view_all:
    pattern: /inbox
    defaults: { _controller: IMDCTerpTubeBundle:Message:viewAllPrivateMessages }
    
imdc_message_delete:
    pattern: /deleteMessage/{messageid}
    defaults: { _controller: IMDCTerpTubeBundle:Message:deleteMessage }
    requirements:
        messageid: \d+
        
imdc_message_archive:
    pattern: /archiveMessage/{messageid}
    defaults: { _controller: IMDCTerpTubeBundle:Message:archiveMessage }
    requirements:
        messageid: \d+
        
imdc_message_view_sent_messages:
    pattern: /sentMessages
    defaults: { _controller: IMDCTerpTubeBundle:Message:viewSentMessages }
    
imdc_message_view_archive:
    pattern: /archivedMessages
    defaults: { _controller: IMDCTerpTubeBundle:Message:viewArchivedMessages }

imdc_message_view_message:
    pattern: /viewMessage/{messageid}
    defaults: { _controller: IMDCTerpTubeBundle:Message:viewMessage }
    
imdc_message_mark_as_read:
    pattern: /messageRead/{messageid}
    defaults: { _controller: IMDCTerpTubeBundle:Message:isMessageRead }
    requirements:
        _method:  POST
        messageid: \d+

imdc_message_reply:
    pattern: /reply/{messageid}
    defaults: { _controller: IMDCTerpTubeBundle:Message:replyToMessage }
    requirements:
        messageid: \d+

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group
    
imdc_initial_noreply_user_create:
    pattern: /createNoReplyOnce
    defaults: { _controller: IMDCTerpTubeBundle:Default:createNoReplyOnce }
    
    
    
imdc_add_to_friends_list:
    pattern: /addToFriendsList/{userid}
    defaults: { _controller: IMDCTerpTubeBundle:FriendsList:add }
    requirements:
        userid: \d+
        
imdc_remove_from_friends_list:
    pattern: /removeFromFriendsList/{userid}/{redirect}
    defaults: { _controller: IMDCTerpTubeBundle:FriendsList:remove, redirect:null }
    requirements:
        userid: \d+
        
imdc_friends_list_show_all:
    pattern: /friends
    defaults: { _controller: IMDCTerpTubeBundle:FriendsList:showAll }
    
    
    
imdc_groups_show_all:
    pattern: /usergroups
    defaults: { _controller: IMDCTerpTubeBundle:UserGroup:index }
    
imdc_group_view:
    pattern: /usergroup/{usergroupid}
    defaults: { _controller: IMDCTerpTubeBundle:UserGroup:viewGroup }
    
imdc_group_create_new:
    pattern: /newusergroup
    defaults: { _controller: IMDCTerpTubeBundle:UserGroup:createNewUserGroup }


imdc_thread_create_new:
    pattern: /thread/new
    defaults: { _controller: IMDCTerpTubeBundle:Thread:createNewThread }
    
imdc_thread_create_new_from_media:
    pattern: /thread/new/{resourceid}
    defaults: { _controller: IMDCTerpTubeBundle:Thread:createNewThreadFromMedia }
    requirements:
        resourceid: \d+
    
imdc_thread_show_recent:
    pattern: /threads
    defaults: { _controller: IMDCTerpTubeBundle:Thread:index }
    
imdc_thread_view_specific:
    pattern: /thread/view/{threadid}
    defaults: { _controller: IMDCTerpTubeBundle:Thread:viewThread }
    requirements:
        threadid: \d+
        
imdc_thread_create_reply_post:
    pattern: /thread/reply/{threadid}
    defaults: { _controller: IMDCTerpTubeBundle:Post:createReplyPost }
    requirements:
        threadid: \d+
    
    
    
imdc_post_create_new:
    pattern: /post/new
    defaults: { _controller: IMDCTerpTubeBundle:Post:createNewPost }
    
imdc_post_show_all:
    pattern: /post/all
    defaults: { _controller: IMDCTerpTubeBundle:Post:index }
    
imdc_post_delete_specific:
    pattern: /post/delete/{postid}/{threadid}
    defaults: { _controller: IMDCTerpTubeBundle:Post:deletePost }
    requirements:
        threadid: \d+
    
imdc_post_delete_specific_ajax:
    pattern: /post/deleteajax/{pid}
    defaults: { _controller: IMDCTerpTubeBundle:Post:deletePostAjax }
    requirements:
        _method: POST
        pid: \d+
    options:
        expose: true
        
imdc_post_edit_specific:
    pattern: /post/edit/{pid}
    defaults: { _controller: IMDCTerpTubeBundle:Post:editPost }
    requirements:
        pid: \d+
        