IMDCTerpTubeBundle_default:
  resource: "@IMDCTerpTubeBundle/Resources/config/routing/default.yml"

IMDCTerpTubeBundle_forum:
  resource: "@IMDCTerpTubeBundle/Resources/config/routing/forum.yml"
  prefix: /forums

IMDCTerpTubeBundle_group:
  resource: "@IMDCTerpTubeBundle/Resources/config/routing/group.yml"
  prefix: /groups

IMDCTerpTubeBundle_home:
  resource: "@IMDCTerpTubeBundle/Resources/config/routing/home.yml"
  prefix: /home

IMDCTerpTubeBundle_member:
  resource: "@IMDCTerpTubeBundle/Resources/config/routing/member.yml"
  prefix: /members

IMDCTerpTubeBundle_post:
  resource: "@IMDCTerpTubeBundle/Resources/config/routing/post.yml"
  prefix: /post

IMDCTerpTubeBundle_thread:
  resource: "@IMDCTerpTubeBundle/Resources/config/routing/thread.yml"
  prefix: /thread










imdc_terp_tube_user_profile_change-password:
    pattern: /profile/{userName}/change-password
    defaults: { _controller: FOSUserBundle:ChangePassword:changePassword }
    methods:  [GET|POST]
    
imdc_terp_tube_user_profile_specific:
    pattern: /profile/{userName}
    defaults: { _controller: IMDCTerpTubeBundle:Profile:showSpecific }
    
imdc_terp_tube_user_profile:
    pattern: /profile/
    defaults: { _controller: IMDCTerpTubeBundle:Profile:show }
    
imdc_terp_tube_user_avatar_edit: 
    pattern: /profile/{userName}/edit/avatar
    defaults: { _controller: IMDCTerpTubeBundle:Profile:updateAvatar }

imdc_terp_tube_user_profile_edit:
    pattern: /profile/{userName}/edit
    defaults: { _controller: IMDCTerpTubeBundle:Profile:edit }
    

imdc_media_chooser_by_type: 
    pattern: /myFiles/choose/{type}
    defaults: { _controller: IMDCTerpTubeBundle:MediaChooserGateway:chooseMediaByType, type: 0 }
    methods: [GET|POST]
    options:
        expose: true
        
imdc_media_simultaneous_record: 
    pattern: /media/record/simultaneous/{mediaID}
    defaults: { _controller: IMDCTerpTubeBundle:Media:simultaneousPreviewAndRecord, url: null }
    options:
        expose: true
        
imdc_files_gateway: 
    pattern: /myFiles
    defaults: { _controller: IMDCTerpTubeBundle:MyFilesGateway:gateway }
    
#imdc_files_gateway_source: 
#    pattern: /myFiles/source/
#    defaults: { _controller: IMDCTerpTubeBundle:MyFilesGateway:gatewaySource }

imdc_files_gateway_interpretations: 
    pattern: /myFiles/interpretations/
    defaults: { _controller: IMDCTerpTubeBundle:MyFilesGateway:gatewayInterpretations }
    
imdc_files_add_gateway: 
    pattern: /myFiles/add
    defaults: { _controller: IMDCTerpTubeBundle:AddFileGateway:gateway}
    
imdc_files_gateway_audio: 
    pattern: /myFiles/add/audio
    defaults: { _controller: IMDCTerpTubeBundle:AddFileGateway:addAudio, url: null }
    options:
        expose: true
    
imdc_files_gateway_video: 
    pattern: /myFiles/add/video
    defaults: { _controller: IMDCTerpTubeBundle:AddFileGateway:addVideo, url: null }
    options:
        expose: true
    
imdc_files_gateway_image: 
    pattern: /myFiles/add/image
    defaults: { _controller: IMDCTerpTubeBundle:AddFileGateway:addImage, url: null }
    options:
        expose: true
    
imdc_files_gateway_record_media: 
    pattern: /myFiles/recordMedia
    defaults: { _controller: IMDCTerpTubeBundle:AddFileGateway:addVideoRecording, url: null }

imdc_files_gateway_other: 
    pattern: /myFiles/add/other
    defaults: { _controller: IMDCTerpTubeBundle:AddFileGateway:addOther, url: null }
    options:
        expose: true

imdc_files_gateway_remove: 
    pattern: /myFiles/delete/{mediaId}
    defaults: { _controller: IMDCTerpTubeBundle:MyFilesGateway:deleteMedia }
    requirements:
        _method:  POST
        mediaId: \d+
    options:
        expose: true
        
imdc_files_gateway_trim: 
    pattern: /myFiles/trim/{mediaId}/{startTime}/{endTime}
    defaults: { _controller: IMDCTerpTubeBundle:MyFilesGateway:trimMedia }
    requirements:
        _method:  POST
        mediaId: \d+
    options:
        expose: true
        
imdc_files_gateway_update: 
    pattern: /myFiles/update/{mediaId}
    defaults: { _controller: IMDCTerpTubeBundle:MyFilesGateway:updateMedia }
    requirements:
        _method:  POST
        mediaId: \d+
    options:
        expose: true
        
imdc_files_gateway_record: 
    pattern: /myFiles/record
    defaults: { _controller: IMDCTerpTubeBundle:AddFileGateway:addRecording, url: null }
    requirements:
        _method:  POST
    options:
        expose: true
        
imdc_files_gateway_add_simultaneous_recording: 
    pattern: /myFiles/add/simultaneous_recording/{sourceMediaID}/{startTime}
    defaults: { _controller: IMDCTerpTubeBundle:AddFileGateway:addSimultaneousRecording, url: null }
    requirements:
        _method:  POST
    options:
        expose: true
        
imdc_files_gateway_preview_compound_media: 
    pattern: /myFiles/preview/compound_media/{compoundMediaId}
    defaults: { _controller: IMDCTerpTubeBundle:MyFilesGateway:previewCompoundMedia, url: null }
#     requirements:
#        _method:  POST
    options:
        expose: true
        
imdc_files_gateway_preview:
    pattern: /myFiles/preview/{mediaId}
    defaults: { _controller: IMDCTerpTubeBundle:MyFilesGateway:previewMedia }
    requirements:
        _method:  POST
#        mediaId: \d+
    options:
       expose: true


imdc_message_create:
    pattern: /createMessage
    defaults: { _controller: IMDCTerpTubeBundle:Message:createMessage }
        
imdc_message_user_specific:
    pattern: /createMessage/{username}
    defaults: { _controller: IMDCTerpTubeBundle:Message:createMessage, username:null }

imdc_message_view_all:
    pattern: /inbox
    defaults: { _controller: IMDCTerpTubeBundle:Message:viewAllPrivateMessages }
    
imdc_message_delete:
    pattern: /deleteMessage/{messageid}
    defaults: { _controller: IMDCTerpTubeBundle:Message:deleteMessage }
    requirements:
        messageid: \d+
        
imdc_message_archive:
    pattern: /archiveMessage/{messageid}
    defaults: { _controller: IMDCTerpTubeBundle:Message:archiveMessage }
    requirements:
        messageid: \d+
        
imdc_message_view_sent_messages:
    pattern: /sentMessages
    defaults: { _controller: IMDCTerpTubeBundle:Message:viewSentMessages }
    
imdc_message_view_archive:
    pattern: /archivedMessages
    defaults: { _controller: IMDCTerpTubeBundle:Message:viewArchivedMessages }

imdc_message_view_message:
    pattern: /viewMessage/{messageid}
    defaults: { _controller: IMDCTerpTubeBundle:Message:viewMessage }
    
imdc_message_mark_as_read:
    pattern: /messageRead/{messageid}
    defaults: { _controller: IMDCTerpTubeBundle:Message:isMessageRead }
    requirements:
        _method:  POST
        messageid: \d+
    options:
        expose: true

imdc_message_reply:
    pattern: /reply/{messageid}
    defaults: { _controller: IMDCTerpTubeBundle:Message:replyToMessage }
    requirements:
        messageid: \d+

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /rolegroup
    
    
    
imdc_add_to_friends_list:
    pattern: /addToFriendsList/{userid}
    defaults: { _controller: IMDCTerpTubeBundle:FriendsList:add }
    requirements:
        userid: \d+
        
imdc_remove_from_friends_list:
    pattern: /removeFromFriendsList/{userid}/{redirect}
    defaults: { _controller: IMDCTerpTubeBundle:FriendsList:remove, redirect:null }
    requirements:
        userid: \d+
        
imdc_friends_list_show_all:
    pattern: /friends
    defaults: { _controller: IMDCTerpTubeBundle:FriendsList:showAll }
    
    
    




    

        
        


IMDCTerpTubeBundle_invitation:
        resource: "@IMDCTerpTubeBundle/Resources/config/routing/invitation.yml"
        prefix:   /invitation
   
imdc_invitations_list:
    pattern: /invitations
    defaults: { _controller: IMDCTerpTubeBundle:Invitation:list }   
   
imdc_invitation_cancel:
    pattern: /invitation/{id}/cancel
    defaults: { _controller: IMDCTerpTubeBundle:Invitation:cancel }   
    
imdc_invitation_reactivate:
    pattern: /invitation/{id}/reactivate
    defaults: { _controller: IMDCTerpTubeBundle:Invitation:reactivate }  
   
imdc_invitation_accept:
    pattern: /invitation/{id}/accept
    defaults: { _controller: IMDCTerpTubeBundle:Invitation:accept }   

imdc_invitation_decline:
    pattern: /invitation/{id}/decline
    defaults: { _controller: IMDCTerpTubeBundle:Invitation:decline }   
   
imdc_mentee_remove:
    pattern: /mentee/{id}/remove
    defaults: { _controller: IMDCTerpTubeBundle:User:menteeRemove }
    
imdc_mentor_remove:
    pattern: /mentor/{id}/remove
    defaults: { _controller: IMDCTerpTubeBundle:User:mentorRemove }
   
   
IMDCTerpTubeBundle_permissions:
    resource: "@IMDCTerpTubeBundle/Resources/config/routing/permissions.yml"
    prefix: /permissions   
 
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
    
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    

    
