imdc_terp_tube_homepage:
    pattern:  /
    defaults: { _controller: IMDCTerpTubeBundle:Default:index }
    
imdc_terp_tube_user_splash:
    pattern: /home/
    defaults: { _controller: IMDCTerpTubeBundle:Home:index }

imdc_terp_tube_user_profile_change-password:
    pattern: /profile/{userName}/change-password
    defaults: { _controller: FOSUserBundle:ChangePassword:changePassword }
    methods:  [GET|POST]
    
imdc_terp_tube_user_profile_specific:
    pattern: /profile/{userName}
    defaults: { _controller: IMDCTerpTubeBundle:Profile:showSpecific }
    
imdc_terp_tube_user_profile:
    pattern: /profile/
    defaults: { _controller: IMDCTerpTubeBundle:Profile:show }
    
imdc_terp_tube_user_profile_edit:
    pattern: /profile/{userName}/edit
    defaults: { _controller: IMDCTerpTubeBundle:Profile:edit }

imdc_message_create:
    pattern: /createMessage
    defaults: { _controller: IMDCTerpTubeBundle:Message:createMessage } 
    
imdc_message_view_all:
    pattern: /inbox
    defaults: { _controller: IMDCTerpTubeBundle:Message:viewAllPrivateMessages }
    
imdc_message_delete:
    pattern: /deleteMessage/{messageid}
    defaults: { _controller: IMDCTerpTubeBundle:Message:deleteMessage }

imdc_message_view_sent_messages:
    pattern: /sentMessages
    defaults: { _controller: IMDCTerpTubeBundle:Message:viewSentMessages }
    
imdc_message_view_archive:
    pattern: /archivedMessages
    defaults: { _controller: IMDCTerpTubeBundle:Message:viewArchivedMessages }

imdc_message_view_message:
    pattern: /viewMessage/{messageid}
    defaults: { _controller: IMDCTerpTubeBundle:Message:viewMessage }
    
imdc_message_mark_as_read:
    pattern: /messageRead/{messageid}
    defaults: { _controller: IMDCTerpTubeBundle:Message:markMessageAsRead }
    requirements:
        _method:  POST

    