imdc_terp_tube_homepage:
    pattern:  /
    defaults: { _controller: IMDCTerpTubeBundle:Default:index }
    
imdc_terp_tube_user_splash:
    pattern: /home/
    defaults: { _controller: IMDCTerpTubeBundle:Home:index }

imdc_terp_tube_user_profile_change-password:
    pattern: /profile/{userName}/change-password
    defaults: { _controller: FOSUserBundle:ChangePassword:changePassword }
    methods:  [GET|POST]
    
imdc_terp_tube_user_profile_specific:
    pattern: /profile/{userName}
    defaults: { _controller: IMDCTerpTubeBundle:Profile:showSpecific }
    
imdc_terp_tube_user_profile:
    pattern: /profile/
    defaults: { _controller: IMDCTerpTubeBundle:Profile:show }
    
imdc_terp_tube_user_avatar_edit: 
    pattern: /profile/{userName}/edit/avatar
    defaults: { _controller: IMDCTerpTubeBundle:Profile:updateAvatar }

imdc_terp_tube_user_profile_edit:
    pattern: /profile/{userName}/edit
    defaults: { _controller: IMDCTerpTubeBundle:Profile:edit }
    

imdc_files_gateway: 
    pattern: /myFiles
    defaults: { _controller: IMDCTerpTubeBundle:MyFilesGateway:gateway }
    
imdc_files_add_gateway: 
    pattern: /myFiles/add
    defaults: { _controller: IMDCTerpTubeBundle:AddFileGateway:gateway, isAjax: false, url: 'imdc_terp_tube_user_profile' }
    
imdc_files_gateway_audio: 
    pattern: /myFiles/add/audio
    defaults: { _controller: IMDCTerpTubeBundle:AddFileGateway:addAudio, isAjax: false, url: 'imdc_terp_tube_user_profile' }
    
imdc_files_gateway_video: 
    pattern: /myFiles/add/video
    defaults: { _controller: IMDCTerpTubeBundle:AddFileGateway:addVideo, isAjax: false, url: imdc_terp_tube_user_profile }
    
imdc_files_gateway_image: 
    pattern: /myFiles/add/image
    defaults: { _controller: IMDCTerpTubeBundle:AddFileGateway:addImage, isAjax: false, url: imdc_terp_tube_user_profile }
    
imdc_files_gateway_record: 
    pattern: /myFiles/add/record
    defaults: { _controller: IMDCTerpTubeBundle:AddFileGateway:addRecording, isAjax: false, url: imdc_terp_tube_user_profile }

imdc_files_gateway_other: 
    pattern: /myFiles/add/other
    defaults: { _controller: IMDCTerpTubeBundle:AddFileGateway:addOther, isAjax: false, url: imdc_terp_tube_user_profile }
    

imdc_message_create:
    pattern: /createMessage
    defaults: { _controller: IMDCTerpTubeBundle:Message:createMessage } 
    
imdc_message_view_all:
    pattern: /inbox
    defaults: { _controller: IMDCTerpTubeBundle:Message:viewAllPrivateMessages }
    
imdc_message_delete:
    pattern: /deleteMessage/{messageid}
    defaults: { _controller: IMDCTerpTubeBundle:Message:deleteMessage }
    requirements:
        messageid: \d+
        
imdc_message_archive:
    pattern: /archiveMessage/{messageid}
    defaults: { _controller: IMDCTerpTubeBundle:Message:archiveMessage }
    requirements:
        messageid: \d+
        
imdc_message_view_sent_messages:
    pattern: /sentMessages
    defaults: { _controller: IMDCTerpTubeBundle:Message:viewSentMessages }
    
imdc_message_view_archive:
    pattern: /archivedMessages
    defaults: { _controller: IMDCTerpTubeBundle:Message:viewArchivedMessages }

imdc_message_view_message:
    pattern: /viewMessage/{messageid}
    defaults: { _controller: IMDCTerpTubeBundle:Message:viewMessage }
    
imdc_message_mark_as_read:
    pattern: /messageRead/{messageid}
    defaults: { _controller: IMDCTerpTubeBundle:Message:isMessageRead }
    requirements:
        _method:  POST
        messageid: \d+

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group
    
imdc_initial_noreply_user_create:
    pattern: /createNoReplyOnce
    defaults: { _controller: IMDCTerpTubeBundle:Default:createNoReplyOnce }