parameters:
#    imdc_terp_tube.example.class: IMDC\TerpTubeBundle\Example

services:
#    imdc_terp_tube.example:
#        class: %imdc_terp_tube.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

     imdc_terptube_user.registration.form.type:
          class: IMDC\TerpTubeBundle\Form\Type\RegistrationFormType
          arguments: [%fos_user.model.user.class%]
          tags:
              - { name: form.type, alias: imdc_terptube_user_registration }