parameters:
#    imdc_terp_tube.example.class: IMDC\TerpTubeBundle\Example
      imdc_terptube.component.authentication.handler.login_success_handler.class: IMDC\TerpTubeBundle\Component\Authentication\Handler\LoginSuccessHandler
      imdc_terptube.component.authentication.handler.logout_success_handler.class: IMDC\TerpTubeBundle\Component\Authentication\Handler\LogoutSuccessHandler
      imdc_terptube.upload_resource_listener.class: IMDC\TerpTubeBundle\EventListener\UploadListener
      imdc_terptube.event.uploadEvent: 'imdc_terptube.event.uploadEvent'

services:
#    imdc_terp_tube.example:
#        class: %imdc_terp_tube.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

     imdc_terptube_user.registration.form.type:
          class: IMDC\TerpTubeBundle\Form\Type\RegistrationFormType
          arguments: [%fos_user.model.user.class%]
          tags:
              - { name: form.type, alias: imdc_terptube_user_registration }
              
     imdc_terptube_user.profile.form.type:
          class: IMDC\TerpTubeBundle\Form\Type\ProfileFormType
          arguments: [%fos_user.model.user.class%]
          tags:
              - { name: form.type, alias: imdc_terptube_user_profile }
              
     imdc_terptube.component.authentication.handler.login_success_handler:
          class: %imdc_terptube.component.authentication.handler.login_success_handler.class%
          arguments: [@router, @security.context]
          tags:
              - {name: 'monolog.logger', channel: 'security' }
              
     imdc_terptube.component.authentication.handler.logout_success_handler:
          class: %imdc_terptube.component.authentication.handler.logout_success_handler.class%
          arguments: [@router, @security.context]
          tags:
              - {name: 'monolog.logger', channel: 'security' }
              
     imdc_terptube.upload_resource_listener:
            class: %imdc_terptube.upload_resource_listener.class%
            arguments: ["@logger", @doctrine]
            tags:
                - { name: kernel.event_listener, event: %imdc_terptube.event.uploadEvent%, method: onUpload}
                - { name: 'monolog.logger', channel: 'imdc' }
     
     imdc_terptube.new_user_intro_email_listener:
            class: IMDC\TerpTubeBundle\EventListener\NewUserRegistrationListener
            arguments: ["@logger", @doctrine]
            tags:
                - { name: kernel.event_subscriber }
                - { name: 'monolog.logger', channel: 'imdc' }
     
     # enable the truncate extension in twig
     twig.extension.text:
          class: Twig_Extensions_Extension_Text
          tags:
              - { name: twig.extension }