parameters:
#    imdc_terp_tube.example.class: IMDC\TerpTubeBundle\Example
      imdc_terptube.component.authentication.handler.login_success_handler.class: IMDC\TerpTubeBundle\Component\Authentication\Handler\LoginSuccessHandler
      imdc_terptube.component.authentication.handler.logout_success_handler.class: IMDC\TerpTubeBundle\Component\Authentication\Handler\LogoutSuccessHandler

services:
#    imdc_terp_tube.example:
#        class: %imdc_terp_tube.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

     imdc_terptube_user.registration.form.type:
          class: IMDC\TerpTubeBundle\Form\Type\RegistrationFormType
          arguments: [%fos_user.model.user.class%]
          tags:
              - { name: form.type, alias: imdc_terptube_user_registration }
              
     imdc_terptube.component.authentication.handler.login_success_handler:
          class: %imdc_terptube.component.authentication.handler.login_success_handler.class%
          arguments: [@router, @security.context]
          tags:
              - {name: 'monolog.logger', channel: 'security' }
              
     imdc_terptube.component.authentication.handler.logout_success_handler:
          class: %imdc_terptube.component.authentication.handler.logout_success_handler.class%
          arguments: [@router, @security.context]
          tags:
              - {name: 'monolog.logger', channel: 'security' }
              