Acme\TaskBundle\Entity\Message:
    type: entity
    table: taskmessage
    repositoryClass: Acme\TaskBundle\Entity\MessageRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        subject:
            type: text
        content:
            type: text
        sentDate:
            type: datetime
    manyToOne:
        owner:
            targetEntity: Person
            inversedBy: sentMessages
    manyToMany:
        recipients:
            targetEntity: Person
            
    lifecycleCallbacks: {  }
