imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@IMDCTerpTubeBundle/Resources/config/constants/Events.xml" }
    - { resource: "@IMDCTerpTubeBundle/Resources/config/constants/Filters.xml" }
    - { resource: "@IMDCTerpTubeBundle/Resources/config/admin.yml" }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    translator:      ~
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

braincrafted_bootstrap:
    less_filter: lessphp
    assets_dir:  %kernel.root_dir%/../vendor/twitter/bootstrap
    jquery_path: %kernel.root_dir%/../vendor/sonata-project/jquery-bundle/Resources/public/jquery-1.10.2.js
    

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ IMDCTerpTubeBundle ]
    #java: /usr/bin/java
    filters:
        lessphp:
          file:       %kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php
          apply_to:   "\.less$"
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
    assets:
        bootstrap_css:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/less/bootstrap.less
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/Bundle/BootstrapBundle/Resources/less/form.less
            filters:
                - lessphp
                - cssrewrite
            output: css/bootstrap.css
        bootstrap_js:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/transition.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/alert.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/button.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/carousel.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/collapse.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/dropdown.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/modal.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/tooltip.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/popover.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/scrollspy.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/tab.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/affix.js
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/Bundle/BootstrapBundle/Resources/js/bc-bootstrap-collection.js
            output: js/bootstrap.js
        jquery:
            inputs:
                - %kernel.root_dir%/../vendor/sonata-project/jquery-bundle/Resources/public/jquery-1.10.2.js
            output: js/jquery.js
        jquery_map:
            inputs:
                - %kernel.root_dir%/../vendor/jquery/jquerymap/jquery-1.10.2.min.map
            output: js/jquery.min.map
        jquery_ui:
            inputs:
                - %kernel.root_dir%/../vendor/sonata-project/jquery-bundle/Resources/public/jquery-ui-1.10.4.js
            output: js/jquery-ui.js
        jquery_autosize:
            inputs:
                - %kernel.root_dir%/../bower_components/jquery-autosize/jquery.autosize.min.js
            output: js/jquery.autosize.min.js
        tag_it_css:
            inputs:
                - %kernel.root_dir%/../bower_components/tag-it/css/jquery.tagit.css
            output: css/jquery.tagit.css
        tag_it_js:
            inputs:
                - %kernel.root_dir%/../bower_components/tag-it/js/tag-it.min.js
            output: js/tag-it.min.js
        recordrtc:
            inputs:
                - %kernel.root_dir%/../node_modules/recordrtc/RecordRTC.js
            output: js/RecordRTC.js
        html5shiv:
            inputs:
                - %kernel.root_dir%/../bower_components/html5shiv/dist/html5shiv.min.js
            output: js/html5shiv.min.js
        require_js:
            inputs:
                - %kernel.root_dir%/../bower_components/requirejs/require.js
            output: js/require.js
        dust_js:
            inputs:
                - %kernel.root_dir%/../bower_components/dustjs/dist/dust-full-0.3.0.min.js
            output: js/dust-full.min.js

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

doctrine_migrations:
    dir_name: %kernel.root_dir%/DoctrineMigrations
    namespace: IMDC\TerpTubeBundle\Migrations
    table_name: migration_versions
    name: Migrations

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

#Uploader bundle configuration
#See https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/index.md for configuration
#vich_uploader:
#    db_driver: orm # or mongodb
#    twig: true
#    gaufrette: false # set to true to enable gaufrette support
#    storage: vich_uploader.storage.file_system
#   mappings:
#        product_image:
#            uri_prefix: web # uri prefix to resource
#            upload_destination: ~ # gaufrette storage fs id, required
#            namer: ~ # specify a file namer service id for this entity, null default
#            directory_namer: ~ # specify a directory namer service id for this entity, null default
#            delete_on_remove: true # determines whether to delete file upon removal of entity
#            inject_on_load: true # determines whether to inject a File instance upon load
        # ... more mappings
      
imdc_terp_tube:
    transcoding:
        ffmpeg_binary: /usr/local/bin/ffmpeg
        ffprobe_binary: /usr/local/bin/ffprobe
        timeout: 3600

ac_transcoding:
    ffmpeg: 
        enabled: true           #if false, other keys need not be specified
        path: /usr/local/bin/ffmpeg
        timeout: 0
    handbrake:
        enabled: false
        


fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: IMDC\TerpTubeBundle\Entity\User
    group:
          group_class: IMDC\TerpTubeBundle\Entity\UserGroup
    registration:
          confirmation:
              enabled: true
          form:
              type: imdc_terptube_user_registration
    profile:
           form:
                type: imdc_terptube_user_profile
                
    from_email:
        address: noreply@terptube
        sender_name: Terptube IMDC

old_sound_rabbit_mq: # see https://github.com/videlalvaro/rabbitmqbundle
    connections:
        default:
            host:      'localhost'
            port:      5672
            user:      'guest'
            password:  'guest'
            vhost:     '/'
            lazy:      false
    producers:
        upload_video:
            connection: default
            exchange_options: {name: 'upload-video', type: direct}
        upload_audio:
            connection: default
            exchange_options: {name: 'upload-audio', type: direct}
    consumers:
        upload_video:
            connection: default
            exchange_options: {name: 'upload-video', type: direct}
            queue_options:    {name: 'upload-video'}
            callback:         upload_video_service
        upload_audio:
            connection: default
            exchange_options: {name: 'upload-audio', type: direct}
            queue_options:    {name: 'upload-audio'}
            callback:         upload_audio_service

knp_time: ~ # Enable the helper for use in templates

knp_paginator:
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig

sonata_admin:
    security:
        handler: sonata.admin.security.handler.role
    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }
            - { position: left, type: sonata.block.service.linkbox } 


sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        # Your other blocks
        sonata.block.service.text: ~
        sonata.block.service.linkbox: ~
        
