IMDC\TerpTubeBundle\Entity\Forum:
    type: entity
    table: null
    repositoryClass: IMDC\TerpTubeBundle\Entity\ForumRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        titleText:
            type: string
            length: '255'
            nullable: true
        description:
            type: text
            nullable: true
        lastActivity:
            type: datetime
        creationDate:
            type: datetime
        mediaDisplayOrder:
            type: array
    manyToOne:
        creator:
            targetEntity: User
            inversedBy: forums
            joinColumn: 
                name: user_id
                referencedColumnName: id
        group:
            targetEntity: UserGroup
            joinColumn:
                name: group_id
                referencedColumnName: id
            inversedBy: forums
        accessType:
            targetEntity: AccessType
            joinColumn:
                name: access_type_id
                referencedColumnName: id
    oneToMany:
        threads:
            targetEntity: Thread
            mappedBy: parentForum
            cascade: ["remove"]
    manyToMany:
        titleMedia:
            targetEntity: Media
            joinTable:
                name: forum_media
                joinColumns:
                    forum_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    media_id:
                        referencedColumnName: id
        forumAdmins:
            targetEntity: User
            joinTable: 
                name: forum_user_admins
                joinColumns:
                    forum_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    user_id:
                        referencedColumnName: id
        forumModerators:
            targetEntity: User
            joinTable:
                name: forum_user_moderators
                joinColumns:
                    forum_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    user_id:
                        referencedColumnName: id
