<?php

namespace IMDC\TerpTubeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use IMDC\TerpTubeBundle\Utils\Utils;
use Symfony\Component\Security\Core\SecurityContext;

/**
 * UserGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserGroupRepository extends EntityRepository
{
    /**
     * @param $user
     * @param $isLoggedIn
     * @param array $sortParams
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getViewableToUserQB($user, $isLoggedIn, $sortParams = array())
    {
        $qb = $this->createQueryBuilder('g')
            ->leftJoin('g.members', 'm');

        $qb->where($qb->expr()->eq('g.visibleToPublic', true));

        if ($isLoggedIn) {
            $qb = $qb->orWhere($qb->expr()->eq('g.visibleToRegisteredUsers', true))
                ->orWhere($qb->expr()->in('m.id', array(
                    $user->getId()
                )));
        }

        return Utils::applySortParams($qb, $sortParams);
    }

    public function getViewableToUser($user, SecurityContext $securityContext, $sortParams = array())
    {
        $isLoggedIn = $securityContext->isGranted('IS_AUTHENTICATED_REMEMBERED');
        $groups = $this->getViewableToUserQB($user, $isLoggedIn, $sortParams)->getQuery()->getResult();

        //FIXME: groups don't use AccessType restrictions
        //return Utils::filterViewableToUser($securityContext, $groups);
        return $groups;
    }
}
