IMDC\TerpTubeBundle\Entity\CompoundMedia: #TODO delete
    type:  entity
    table: compound_media
    repositoryClass: IMDC\TerpTubeBundle\Entity\CompoundMediaRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        type: #0-simultaneous Recording, 1-consecutiveRecording
            type: smallint
        targetStartTime:
            type: decimal
            precision: 12
            scale: 2
        
    manyToOne:
        source: #media object to hold the source for the interpretation
            targetEntity: Media
            joinColumn:
                name: source_id
                referencedColumnName: id
        target: #media object to hold the actual interpretation
            targetEntity: Media
            joinColumn:
                name: target_id
                referencedColumnName: id       
