IMDC\TerpTubeBundle\Entity\InvitationType:
    type: entity
    table: invitation_type
    fields:
        id:
            type: integer
            id: true
        name:
            type: string
    lifecycleCallbacks: {  }
