IMDC\TerpTubeBundle\Entity\Language:
    type: entity
    table: language
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
                 
    fields: 
        name:
            type: string
            length: 50
        type:       #spoken, sign
            type: smallint
        proficiency:    #scale?
            type: smallint
              