IMDC\TerpTubeBundle\Entity\Media:
    type: entity
    inheritanceType: JOINED
    discriminatorColumn:
        name: discr
        type: string
    discriminatorMap:
        media: Media
        interpretation: Interpretation
    table: media
    repositoryClass: IMDC\TerpTubeBundle\Entity\MediaRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        type: #0-image, 1-video, 2-audio
            type: smallint
        title:  #user given title of the media
            type: string
            length: 255
            nullable: true;
        isReady: #0-no, 1-webm-ready, 2-mpeg-ready, 3-ready
            type: smallint
        pendingOperations:
            type: array
            nullable: true;
        thumbnailPath:
            type: string
            length: 10
            nullable: true
    manyToOne:
        owner:
            targetEntity: User
            inversedBy: resourceFiles
            joinColumn:
                name: owner_id
                referencedColumnName: id
    oneToOne:
        metaData: #metadata object to hold the information about the data
            targetEntity: MetaData
            joinColumn:
                name: meta_data
                referencedColumnName: id
            cascade: ["all"]
        sourceResource:
            targetEntity: ResourceFile
            joinColumn:
                name: source_resource_id
                referencedColumnName: id
            cascade: ["all"]
    manyToMany:
        resources:
            targetEntity: ResourceFile
            joinTable:
                name: media_resources
                joinColumns:
                    media_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    resource_id:
                        referencedColumnName: id
                        unique: true
    lifecycleCallbacks:
        preRemove: [ removeThumbnail ]
