IMDC\TerpTubeBundle\Entity\Media:
    type:  entity
    table: media
    repositoryClass: IMDC\TerpTubeBundle\Entity\MediaRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        type: #0-image, 1-video, 2-audio
            type: smallint
        title:  #user given title of the media
            type: string
            length: 255
            nullable: true;
        isReady: #0-no, 1-webm-ready, 2-mpeg-ready, 3-ready
            type: smallint
        
    manyToOne:
        owner:
            targetEntity: User
            inversedBy: resourceFiles
            joinColumn:
                name: owner_id
                referencedColumnName: id
                
    oneToOne:
        metaData: #metadata object to hold the information about the data
            targetEntity: MetaData
            joinColumn:
                name: meta_data
                referencedColumnName: id
            cascade: ["all"]
                
        resource: #resource object to hold the data
            targetEntity: ResourceFile
            joinColumn:
                name: resource_id
                referencedColumnName: id
            cascade: ["all"]
