IMDC\TerpTubeBundle\Entity\Message:
    type: entity
    table: message
    manyToOne:
        user:
            targetEntity: User
            inversedBy: messages
            joinColumn:
                name: user_id
                referencedColumnName: id
    repositoryClass: IMDC\TerpTubeBundle\Entity\MessageRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        subject:
            type: string
            length: '255'
        content:
            type: text
        sentDate:
            type: datetime
    lifecycleCallbacks: 
        prePersist: [setSentValue]
