IMDC\TerpTubeBundle\Entity\Message:
    type: entity
    table: message
    repositoryClass: IMDC\TerpTubeBundle\Entity\MessageRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        subject:
            type: string
            length: '255'
        content:
            type: text
        sentDate:
            type: datetime
        tempRead:
            type: boolean
            nullable: true
    manyToOne:
        owner:
            targetEntity: User
            inversedBy: sentMessages
    manyToMany:
        recipients:
            targetEntity: User
            joinTable:
                name: messages_recipients_users
                joinColumns:
                    message_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    user_id:
                        referencedColumnName: id
        usersRead:
            targetEntity: User
            joinTable: 
                name: messages_readby_users
                joinColumns:
                    message_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    user_id:
                        referencedColumnName: id
        usersArchived:
            targetEntity: User
            joinTable:
                name: messages_archived_users
                joinColumns:
                    message_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    user_id:
                        referencedColumnName: id
        usersDeleted:
            targetEntity: User
            joinTable:
                name: messages_deleted_users
                joinColumns:
                    message_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    user_id:
                        referencedColumnName: id
    lifecycleCallbacks: 
        prePersist: [setSentValue]
