IMDC\TerpTubeBundle\Entity\Permissions:
    type: entity
    table: null
    repositoryClass: IMDC\TerpTubeBundle\Entity\PermissionsRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        accessLevel:
            type: smallint
            default: 0
    manyToMany: 
        userGroupsWithAccess: # one to many unidirectional
            targetEntity: UserGroup
            joinTable:
                name: permissions_usergroups
                joinColumns:
                    permissions_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    usergroup_id:
                        referencedColumnName: id
                        unique: true
        usersWithAccess: # one to many unidirectional
            targetEntity: User
            joinTable:
                name: users_permissions
                joinColumns:
                    permissions_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    user_id:
                        referencedColumnName: id
                        unique: true
    lifecycleCallbacks: {  }
