IMDC\TerpTubeBundle\Entity\Permissions:
    type: entity
    table: null
    repositoryClass: IMDC\TerpTubeBundle\Entity\PermissionsRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        publicAccess:
            type: boolean
        usersWithLinkHaveAccess:
            type: boolean
        privateAccess:
            type: boolean
    oneToOne:
        friendsOfMember: 
            targetEntity: User
            joinColumn:
                name: friends_of_member
                referencedColumnName: id
            cascade: ["all"]
    manyToMany: 
        groupsWithAccess: # one to many unidirectional
            targetEntity: UserGroup
            joinTable:
                name: permissions_usergroups
                joinColumns:
                    permissions_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    usergroup_id:
                        referencedColumnName: id
                        unique: true
        usersWithAccess: # one to many unidirectional
            targetEntity: User
            joinTable:
                name: users_permissions
                joinColumns:
                    permissions_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    user_id:
                        referencedColumnName: id
                        unique: true
        
    lifecycleCallbacks: {  }
