IMDC\TerpTubeBundle\Entity\Post:
    type: entity
    table: post
    repositoryClass: IMDC\TerpTubeBundle\Entity\PostRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        content:
            type: text
        isDeleted:
            type: boolean
        created:
            type: datetime
        editedAt:
            type: datetime
            nullable: true
        startTime:
            type: decimal
            nullable: true
        endTime:
            type: decimal
            nullable: true
    manyToOne:
        author:
            targetEntity: User
            inversedBy: posts
        parentThread:
            targetEntity: Thread
            inversedBy: posts
    lifecycleCallbacks: {  }
