IMDC\TerpTubeBundle\Entity\Post:
    type: entity
    table: post
    repositoryClass: IMDC\TerpTubeBundle\Entity\PostRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        content:
            type: text
        isDeleted:
            type: boolean
        created:
            type: datetime
        editedAt:
            type: datetime
            nullable: true
        startTime:
            type: decimal
            precision: 12
            scale: 2
            nullable: true
        endTime:
            type: decimal
            precision: 12
            scale: 2
            nullable: true
        isTemporal:
            type: boolean
            nullable: true
    manyToMany: 
        attachedFile:  #many-to-many relationship
            targetEntity: Media
            joinTable:
                name: posts_attached_files
                joinColumns:
                    post_id: 
                        referencedColumnName: id
                inverseJoinColumns:
                    media_id:
                        referencedColumnName: id  
            nullable: true;
    manyToOne:
        author:
            targetEntity: User
            inversedBy: posts
        parentThread:
            targetEntity: Thread
            inversedBy: posts
        editedBy:
            targetEntity: User
            inversedBy: editedPosts
            nullable: true;
    lifecycleCallbacks: {  }
