IMDC\TerpTubeBundle\Entity\ResourceFile:
    type:  entity
    table: resource_file
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        filename:
               type: text

    oneToOne:
        resource: #resource object to hold the data
            targetEntity: Media
            joinColumn:
                name: media_id
                referencedColumnName: id
            inverseColumn:
                name: resource
                referencedColumnName: id
                