IMDC\TerpTubeBundle\Entity\ResourceFile:
    type:  entity
    table: resource_file
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        filename:
               type: text

    manyToOne:
        owner:
            targetEntity: User
            inversedBy: resourceFiles
            joinColumn:
                name: owner_id
                referencedColumnName: id
                