# src/IMDC/TerpTubeBundle/REsources/config/doctrine/RoleGroup.orm.yml

IMDC\TerpTubeBundle\Entity\RoleGroup:
    type: entity
    table: fos_rolegroup
    id:
        id:
            type: integer
            generator: 
                strategy: AUTO
                