IMDC\TerpTubeBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    oneToMany:
        sentMessages:
            targetEntity: Message
            mappedBy: owner
        resourceFiles:
            targetEntity: Media
            mappedBy: owner
    oneToOne:
        profile:
            targetEntity: UserProfile
            joinColumn:
                name: profile_id
                referencedColumnName: id
            cascade: ["all"]
    manyToMany:
        #functions as one to many
        receivedMessages:
            targetEntity: Message
            joinTable:
                name: users_received_messages
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    message_id:
                        referencedColumnName: id
                        unique: true
        #functions as one to many
        readMessages:
            targetEntity: Message
            joinTable:
                name: users_read_messages
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    message_id:
                        referencedColumnName: id
                        unique: true
        #functions as one to many
        archivedMessages:
            targetEntity: Message
            joinTable:
                name: users_archived_messages
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    message_id:
                        referencedColumnName: id
                        unique: true
        #functions as one to many
        deletedMessages:
            targetEntity: Message
            joinTable:
                name: users_deleted_messages
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    message_id:
                        referencedColumnName: id
                        unique: true
        userGroups:
            targetEntity: UserGroup
            joinTable:
                name: fos_user_group
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    userGroup_id:
                        referencedColumnName: id