IMDC\TerpTubeBundle\Entity\User:
    type:  entity
    table: fos_user
    oneToMany:
        messages:
            targetEntity: Message
            mappedBy: user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
                
    oneToOne:
        profile:
            targetEntity: UserProfile
            joinColumn:
                name: profile_id
                referencedColumnName: id
            cascade: ["all"]
              