IMDC\TerpTubeBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    oneToMany:
        sentMessages:
            targetEntity: Message
            mappedBy: sender
        receivedMessages:
            targetEntity: Message
            mappedBy: receipients
    oneToOne:
        profile:
            targetEntity: UserProfile
            joinColumn:
                name: profile_id
                referencedColumnName: id
            cascade: ["all"]
    oneToMany:
        resourceFiles:
            targetEntity: Media
            mappedBy: owner
              