IMDC\TerpTubeBundle\Entity\UserProfile:
    type:   entity
    table:  user_profile
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
     
    manyToMany:
        languages:    #Have an array of languages (one-to-many relationship)
            targetEntity: Language
            joinTable:
                name: user_language
                joinColumns:
                    user_profile_id:
                      referencedColumnName: id
                inverseJoinColumns:
                    language_id:
                      referencedColumnName: id
                      unique: true          
            nullable: true;  
    fields: 
        firstName:
            type: string
            length: 255
        lastName:
            type: string
            length: 255
        middleName:
            type: string
            length: 255
        birthDate:
            type: date
        city:
            type: string
            length: 255
        country:
            type: string
            length: 255
        gender:
            type: string
            length: 1
            nullable: true
        #education
        #Affiliations/memberships/organizations ?
            #Deaf community connection ? (deaf parents, etc)
        #Photo/icon
        #Video bio file
        #Text bio (can this option be greyed out until a video bio is uploaded?)
        #Skype name
        #Interested in being mentored by an ASL mentor? Yes/No/null
        #Interested in being mentored by another interpreter? Yes/No/null
        #Interested in being an ASL mentor? Yes/No/null
        #Interested in being an interpreter mentor? Yes/No/null
        #Interests and specialties fields. Radio buttons for the common options.
        #Seperate tab for professional experience in profile