IMDC\TerpTubeBundle\Entity\UserGroup:
    type: entity
    table: fos_group
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        dateCreated:
            type: datetime
    manyToOne:
        userFounder:
            targetEntity: User
            joinColumn:
                name: userFounder_id
                referencedColumnName: id
    lifecycleCallbacks: 
        prePersist: [setDateCreatedToNow]
