IMDC\TerpTubeBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    oneToMany:
        sentMessages:
            targetEntity: Message
            inversedBy: owner
    oneToMany:
        receivedMessages:
            targetEntity: Message
            joinTable:
                name: users_received_messages
                joinColumns:
                    user_id: 
                        referencedColumnName: id
                inverseJoinColumns:
                    message_id:
                        referencedColumnName: id
    oneToOne:
        profile:
            targetEntity: UserProfile
            joinColumn:
                name: profile_id
                referencedColumnName: id
            cascade: ["all"]
    oneToMany:
        resourceFiles:
            targetEntity: Media
            mappedBy: owner
              