IMDC\TerpTubeBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    oneToMany:
        sentMessages:
            targetEntity: Message
            mappedBy: owner
        receivedMessages:
            targetEntity: Message
            mappedBy: owner
        resourceFiles:
            targetEntity: Media
            mappedBy: owner
    oneToOne:
        profile:
            targetEntity: UserProfile
            joinColumn:
                name: profile_id
                referencedColumnName: id
            cascade: ["all"]
        
              