imdc_group_list:
  pattern: /
  defaults: { _controller: IMDCTerpTubeBundle:UserGroup:index }

imdc_group_view:
  pattern: /{usergroupid}
  defaults: { _controller: IMDCTerpTubeBundle:UserGroup:viewGroup }
  requirements:
    usergroupid: \d+

imdc_group_new:
  pattern: /new
  defaults: { _controller: IMDCTerpTubeBundle:UserGroup:createNewUserGroup }

imdc_group_edit:
  pattern: /{usergroupid}/edit
  defaults: { _controller: IMDCTerpTubeBundle:UserGroup:editUserGroup }
  requirements:
    usergroupid: \d+

imdc_group_delete:
  pattern: /{usergroupid}/delete
  defaults: { _controller: IMDCTerpTubeBundle:UserGroup:deleteUserGroup }
  requirements:
    usergroupid: \d+

imdc_group_my_groups:
  pattern: /myGroups
  defaults: { _controller: IMDCTerpTubeBundle:UserGroup:myGroupShow }

imdc_group_join:
  pattern: /{usergroupid}/join
  defaults: { _controller: IMDCTerpTubeBundle:UserGroup:joinUserGroup }
  requirements:
    usergroupid: \d+

imdc_group_add_members:
  pattern: /{usergroupid}/add
  defaults: { _controller: IMDCTerpTubeBundle:UserGroup:addMembers }
  requirements:
    usergroupid: \d+
