imdc_group_list:
  pattern: /
  defaults: { _controller: IMDCTerpTubeBundle:UserGroup:list }

imdc_group_new:
  pattern: /new
  defaults: { _controller: IMDCTerpTubeBundle:UserGroup:new }

imdc_group_view:
  pattern: /{groupId}
  defaults: { _controller: IMDCTerpTubeBundle:UserGroup:view }
  requirements:
    groupId: \d+

imdc_group_edit:
  pattern: /{groupId}/edit
  defaults: { _controller: IMDCTerpTubeBundle:UserGroup:edit }
  requirements:
    groupId: \d+

imdc_group_delete:
  pattern: /{groupId}/delete
  defaults: { _controller: IMDCTerpTubeBundle:UserGroup:delete }
  requirements:
    _method: POST
    groupId: \d+
  options:
    expose: true

imdc_group_my_groups:
  pattern: /myGroups
  defaults: { _controller: IMDCTerpTubeBundle:UserGroup:listMyGroups }

imdc_group_join:
  pattern: /{groupId}/join
  defaults: { _controller: IMDCTerpTubeBundle:UserGroup:join }
  requirements:
    groupId: \d+

imdc_group_leave:
  pattern: /{groupId}/leave
  defaults: { _controller: IMDCTerpTubeBundle:UserGroup:leave }
  requirements:
    groupId: \d+

imdc_group_message:
  pattern: /{groupId}/message
  defaults: { _controller: IMDCTerpTubeBundle:UserGroup:message }
  requirements:
    groupId: \d+

imdc_group_add_members:
  pattern: /{groupId}/addMembers
  defaults: { _controller: IMDCTerpTubeBundle:UserGroup:addMembers }
  requirements:
    groupId: \d+

imdc_group_delete_members:
  pattern: /{groupId}/deleteMembers
  defaults: { _controller: IMDCTerpTubeBundle:UserGroup:deleteMembers }
  requirements:
    groupId: \d+
