imdc_media_list:
  type: rest
  resource: IMDC\TerpTubeBundle\Controller\MediaController
  options:
    expose: true

imdc_media_get:
  type: rest
  resource: IMDC\TerpTubeBundle\Controller\MediaController
  requirements:
    mediaId: \d+
  options:
    expose: true

imdc_media_edit:
  type: rest
  resource: IMDC\TerpTubeBundle\Controller\MediaController
  requirements:
    mediaId: \d+
  options:
    expose: true

imdc_media_delete:
  type: rest
  resource: IMDC\TerpTubeBundle\Controller\MediaController
  requirements:
    mediaId: \d+
  options:
    expose: true

imdc_media_trim:
  type: rest
  resource: IMDC\TerpTubeBundle\Controller\MediaController
  requirements:
    mediaId: \d+
  options:
    expose: true
