imdc_member_list:
  pattern: /
  defaults: { _controller: IMDCTerpTubeBundle:User:index }

imdc_member_friend_add:
  pattern: /friends/{userid}/add
  defaults: { _controller: IMDCTerpTubeBundle:Contact:add }
  requirements:
    userid: \d+

imdc_member_friend_remove:
  pattern: /friends/{userid}/remove/{redirect}
  defaults: { _controller: IMDCTerpTubeBundle:Contact:remove, redirect:null }
  requirements:
    userid: \d+

imdc_member_mentor_remove:
    pattern: /mentor/{id}/remove
    defaults: { _controller: IMDCTerpTubeBundle:User:mentorRemove }

imdc_member_mentee_remove:
    pattern: /mentee/{id}/remove
    defaults: { _controller: IMDCTerpTubeBundle:User:menteeRemove }
