imdc_message_inbox:
  pattern: /inbox
  defaults: { _controller: IMDCTerpTubeBundle:Message:viewAllPrivateMessages }

imdc_message_sent:
  pattern: /sent
  defaults: { _controller: IMDCTerpTubeBundle:Message:viewSentMessages }

imdc_message_archive:
  pattern: /archived
  defaults: { _controller: IMDCTerpTubeBundle:Message:viewArchivedMessages }

imdc_message_new:
  pattern: /new
  defaults: { _controller: IMDCTerpTubeBundle:Message:createMessage }

imdc_message_new_user:
  pattern: /new/{username}
  defaults: { _controller: IMDCTerpTubeBundle:Message:createMessage, username:null }

imdc_message_view:
  pattern: /{messageid}
  defaults: { _controller: IMDCTerpTubeBundle:Message:viewMessage }
  requirements:
    messageid: \d+

imdc_message_archive_message:
  pattern: /{messageid}/archive
  defaults: { _controller: IMDCTerpTubeBundle:Message:archiveMessage }
  requirements:
    messageid: \d+

imdc_message_mark_as_read:
  pattern: /{messageid}/read
  defaults: { _controller: IMDCTerpTubeBundle:Message:isMessageRead }
  requirements:
    _method:  POST
    messageid: \d+
  options:
    expose: true

imdc_message_reply:
  pattern: /{messageid}/reply
  defaults: { _controller: IMDCTerpTubeBundle:Message:replyToMessage }
  requirements:
    messageid: \d+

imdc_message_delete:
  pattern: /{messageid}/delete
  defaults: { _controller: IMDCTerpTubeBundle:Message:deleteMessage }
  requirements:
    messageid: \d+
