imdc_myfiles_list:
  pattern: /
  defaults: { _controller: IMDCTerpTubeBundle:MyFilesGateway:list }
  options:
    expose: true

imdc_myfiles_add_recording:
  pattern: /add/recording
  defaults: { _controller: IMDCTerpTubeBundle:MyFilesGateway:addRecording }
  methods: [POST]
  options:
    expose: true

imdc_myfiles_add:
  pattern: /add
  defaults: { _controller: IMDCTerpTubeBundle:MyFilesGateway:add }
  methods: [POST]
  options:
    expose: true
