#permissions:
#    pattern:  /
#    defaults: { _controller: "IMDCTerpTubeBundle:Permissions:index" }
#
#permissions_show:
#    pattern:  /{id}/show
#    defaults: { _controller: "IMDCTerpTubeBundle:Permissions:show" }
#
#permissions_new:
#    pattern:  /new
#    defaults: { _controller: "IMDCTerpTubeBundle:Permissions:new" }
#
#permissions_create:
#    pattern:  /create
#    defaults: { _controller: "IMDCTerpTubeBundle:Permissions:create" }
#    requirements: { _method: post }
#
#permissions_edit:
#    pattern:  /{id}/edit
#    defaults: { _controller: "IMDCTerpTubeBundle:Permissions:edit" }
#
#permissions_update:
#    pattern:  /{id}/update
#    defaults: { _controller: "IMDCTerpTubeBundle:Permissions:update" }
#    requirements: { _method: post|put }
#
#permissions_delete:
#    pattern:  /{id}/delete
#    defaults: { _controller: "IMDCTerpTubeBundle:Permissions:delete" }
#    requirements: { _method: post|delete }
