#imdc_post_show_all: #TODO delete
  #pattern: /all
  #defaults: { _controller: IMDCTerpTubeBundle:Post:index }

#imdc_post_create_new: #TODO delete
  #pattern: /new
  #defaults: { _controller: IMDCTerpTubeBundle:Post:createNewPost }

#imdc_thread_create_reply_post: #TODO delete
  #pattern: /reply/thread/{threadid}
  #defaults: { _controller: IMDCTerpTubeBundle:Post:createReplyPost }
  #requirements:
    #threadid: \d+

imdc_post_reply:
  pattern: /{pid}/reply
  defaults: { _controller: IMDCTerpTubeBundle:Post:reply }
  requirements:
    pid: \d+
  options:
    expose: true

imdc_post_edit:
  pattern: /{pid}/edit
  defaults: { _controller: IMDCTerpTubeBundle:Post:edit }
  requirements:
    pid: \d+
  options:
    expose: true

#imdc_post_delete: #TODO delete
  #pattern: /delete/{postid}/thread/{threadid}
  #defaults: { _controller: IMDCTerpTubeBundle:Post:deletePost }
  #requirements:
    #postid: \d+
    #threadid: \d+

imdc_post_delete_ajax: #TODO merge into imdc_post_delete
  pattern: /{pid}/deleteajax
  defaults: { _controller: IMDCTerpTubeBundle:Post:deletePostAjax }
  requirements:
    _method: POST
    pid: \d+
  options:
    expose: true
