imdc_post_reply:
  pattern: /{pid}/reply
  defaults: { _controller: IMDCTerpTubeBundle:Post:new, threadId: null }
  requirements:
    pid: \d+
  options:
    expose: true

imdc_post_edit:
  pattern: /{pid}/edit
  defaults: { _controller: IMDCTerpTubeBundle:Post:edit }
  requirements:
    pid: \d+
  options:
    expose: true

imdc_post_delete:
  pattern: /{pid}/delete
  defaults: { _controller: IMDCTerpTubeBundle:Post:deletePostAjax }
  requirements:
    _method: POST
    pid: \d+
  options:
    expose: true
