imdc_profile_me:
  pattern: /
  defaults: { _controller: IMDCTerpTubeBundle:Profile:show }

imdc_profile_user:
  pattern: /user/{userName}
  defaults: { _controller: IMDCTerpTubeBundle:Profile:showSpecific }

imdc_profile_edit:
  pattern: /edit
  defaults: { _controller: IMDCTerpTubeBundle:Profile:edit }

imdc_profile_edit_avatar:
  pattern: /edit/avatar
  defaults: { _controller: IMDCTerpTubeBundle:Profile:updateAvatar }
