imdc_thread_new_from_media:
  pattern: /new/myFiles/{resourceid}
  defaults: { _controller: IMDCTerpTubeBundle:Thread:createNewThreadFromMedia }
  requirements:
    resourceid: \d+
  options:
    expose: true

imdc_thread_new_under_forum:
  pattern: /new/forum/{forumid}
  defaults: { _controller: IMDCTerpTubeBundle:Thread:createNewThread }
  requirements:
    forumid: \d+

imdc_thread_view:
  pattern: /{threadid}
  defaults: { _controller: IMDCTerpTubeBundle:Thread:view }
  requirements:
    threadid: \d+

imdc_thread_edit:
  pattern: /{threadid}/edit
  defaults: { _controller: IMDCTerpTubeBundle:Thread:editThread }
  requirements:
    threadid: \d+

imdc_thread_delete:
  pattern: /{threadid}/delete
  defaults: { _controller: IMDCTerpTubeBundle:Thread:deleteThread }
  requirements:
    threadid: \d+

imdc_thread_new_post:
  pattern: /{threadId}/reply
  defaults: { _controller: IMDCTerpTubeBundle:Post:new, pid: null }
  requirements:
    threadId: \d+
  options:
    expose: true
