<?php

namespace IMDC\TerpTubeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ForumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumRepository extends EntityRepository
{
    public function getMostRecentForums($limit=30)
    {
        $query = $this->getEntityManager()->createQuery(
                            'SELECT f
                            FROM IMDCTerpTubeBundle:Forum f
                            ORDER BY f.lastActivity DESC'
        );
        $query->setMaxResults($limit);
         
        return $query->getResult();
    }
    
    public function getRecentlyCreatedForums($limit=30)
    {
        $query = $this->getEntityManager()->createQuery(
                    'SELECT f
                     FROM IMDCTerpTubeBundle:Forum f
                     ORDER BY f.creationDate DESC'
        );
        $query->setMaxResults($limit);
        
        return $query->getResult();
    }
}
