<?php

namespace IMDC\TerpTubeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ForumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumRepository extends EntityRepository
{
    public function getMostRecentForums($limit=30)
    {
        $query = $this->getEntityManager()->createQuery(
                            'SELECT f
                            FROM IMDCTerpTubeBundle:Forum f
                            ORDER BY f.lastActivity DESC'
        );
        $query->setMaxResults($limit);
         
        return $query->getResult();
    }
    
    public function getRecentlyCreatedForums($limit=30)
    {
        $query = $this->getEntityManager()->createQuery(
                    'SELECT f
                     FROM IMDCTerpTubeBundle:Forum f
                     ORDER BY f.creationDate DESC'
        );
        $query->setMaxResults($limit);
        
        return $query->getResult();
    }
    
    /**
     * Does this belong here, or in the Thread Repository?
     * @param unknown $fid
     */
    public function getTopLevelThreadsForForum($fid)
    {
        $dql = "SELECT t
	            FROM IMDCTerpTubeBundle:Thread t
	            WHERE t.parentForum IS NOT NULL
	            AND t.parentForum = :fid
	            ORDER BY t.lastPostAt DESC";
        
        $query = $this->getEntityManager()->createQuery($dql)->setParameter('fid', $fid);
        return $query->getResult();
    }
}
