<?php

namespace IMDC\TerpTubeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
	public function getRecentPosts($limit=30)
	{
		$query = $this->getEntityManager()
		->createQuery
			('SELECT p
			FROM IMDCTerpTubeBundle:Post p
            ORDER BY p.created DESC
            ');
		$query->setMaxResults($limit);
		 
		return $query->getResult();
	}
}
