<?php

namespace IMDC\TerpTubeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ThreadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThreadRepository extends EntityRepository
{
    public function getMostRecentThreads($limit=30)
    {
        $query = $this->getEntityManager()
                      ->createQuery
                      ('SELECT t
                        FROM IMDCTerpTubeBundle:Thread t
                        ORDER BY t.creationDate DESC
                       ');
        $query->setMaxResults($limit);
         
        return $query->getResult();
    }
}
