<?php

namespace IMDC\TerpTubeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use IMDC\TerpTubeBundle\Entity\User;

/**
 * UserGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserGroupRepository extends EntityRepository
{
	public function getPublicallyVisibleGroups($limit=0)
	{
		$query = $this->getEntityManager()
						->createQuery('
                            SELECT g
                            FROM IMDCTerpTubeBundle:UserGroup g
                            WHERE g.visibleToPublic = TRUE
                            ORDER BY g.dateCreated DESC');

        if ($limit > 0) {
            $query->setMaxResults($limit);
        }

		return $query->getResult();
	}
	
	public function getGroupsForUser(User $user, $limit=0)
    {
        $query = $this->getEntityManager()
                ->createQuery('
                    SELECT g
                    FROM IMDCTerpTubeBundle:UserGroup g
                    JOIN IMDCTerpTubeBundle:User u
                    WHERE u.id = :uid
                ')
                ->setParameter('uid', $user->getId());

        if ($limit > 0) {
            $query->setMaxResults($limit);
        }

        return $query->getResult();
    }
}