<?php

namespace IMDC\TerpTubeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserGroupRepository extends EntityRepository
{
	public function getPublicallyVisibleGroups()
	{
		$query = $this->getEntityManager()
						->createQuery
							('SELECT g
		                    	FROM IMDCTerpTubeBundle:UserGroup g
								WHERE g.visibleToPublic = TRUE
		                        ORDER BY g.dateCreated DESC
	                        ');
		//$query->setMaxResults($limit);
		 
		return $query->getResult();
	}
}